# Generated by Django 4.2.4 on 2023-08-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('numbmanage', '0002_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class',
            old_name='name',
            new_name='cname',
        ),
    ]
