# Generated by Django 4.2.4 on 2023-08-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('numbmanage', '0005_alter_userlist_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlist',
            name='gender',
            field=models.SmallIntegerField(choices=[(1, '男'), (2, '女')], verbose_name='性别'),
        ),
    ]
