# Generated by Django 4.2.4 on 2023-08-23 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('numbmanage', '0006_alter_userlist_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gradelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
            ],
        ),
        migrations.AddField(
            model_name='userlist',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='numbmanage.gradelist'),
        ),
    ]
