# Generated by Django 4.1.7 on 2023-03-30 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study01', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='age',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='account',
            field=models.CharField(default='chenhonglin', max_length=12),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='tel',
            field=models.CharField(default='Null', max_length=11),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(default='Null', max_length=32),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
