# Generated by Django 4.1.7 on 2023-04-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study01', '0002_remove_userinfo_age_userinfo_account_userinfo_tel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Null', max_length=32)),
                ('tel', models.CharField(default='Null', max_length=11)),
                ('t01', models.CharField(default='Null', max_length=12)),
            ],
        ),
    ]
