# Generated by Django 4.1.7 on 2023-04-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('study01', '0003_test'),
    ]

    operations = [
        migrations.RenameField(
            model_name='test',
            old_name='t01',
            new_name='t_01',
        ),
    ]
