# Generated by Django 4.2.4 on 2023-08-08 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study01', '0004_rename_t01_test_t_01'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(default='uname', max_length=32),
        ),
    ]
